export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const REMOVE_A_ITEM = 'REMOVE_A_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const CHANGE_DROPDOWN = 'CHANGE_DROPDOWN'
export const GET_TOTAL = 'GET_TOTAL'
export const DELETE_ITEM = 'DELETE_ITEM'
export const GET_DIRECTORY = 'GET_DIRECTORY'
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS'


//Shop Actions Types
export const shopActionsTypes = {
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAIL: 'FETCH_COLLECTION_FAIL'
}